name: Python to C++ Code Generation

on:
  push:
    branches:
      - feature/**
    paths:
      - 'source/**/*.py'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-shared:
    uses: Modeling-Coding-Automation-Project/MCAP_actions/.github/workflows/python_to_cpp.yml@main
    with:
      submodules: 'false'     # Set to 'true' if your repository uses git submodules
      # ai_model: "claude-sonnet-4.5"
    secrets:
      COPILOT_GITHUB_TOKEN: ${{ secrets.COPILOT_GITHUB_TOKEN }}
